# Generated by Django 2.2.6 on 2020-04-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter event name', max_length=300)),
                ('description', models.TextField(blank=True, help_text='enter event description')),
            ],
        ),
    ]
