# Generated by Django 2.2.6 on 2020-04-06 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassName',
            new_name='Events',
        ),
    ]
