# Generated by Django 2.2.6 on 2020-04-06 14:42

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_auto_20200406_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='events',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
