# Generated by Django 2.2.6 on 2020-04-06 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200406_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
