# Generated by Django 2.2.6 on 2020-04-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200406_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('conference', 'Conference Of Convention'), ('concert', 'Concert'), ('seminar', 'Seminar Or Talk'), ('festival', 'Festival Of Fair'), ('performance', 'Performance Or Live Show'), ('workshop', 'Class Training Or Workshop'), ('networking', 'Meeting Or Networking Event'), ('party', 'Party or Social Gathering'), ('attraction', 'Attraction'), ('appearance', 'Appearance Or Singing')], default=None, max_length=20),
        ),
    ]
