# Generated by Django 2.2.6 on 2020-04-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20200406_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(blank=True, help_text='Enter event name', max_length=300, null=True),
        ),
    ]
