# Generated by Django 2.2.6 on 2020-04-06 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_auto_20200406_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
