# Generated by Django 2.2.6 on 2020-04-06 16:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0018_delete_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Enter event name', max_length=300, null=True)),
                ('description', models.TextField(blank=True, help_text='enter event description')),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('event_venue', models.CharField(blank=True, choices=[('venue', 'Venue'), ('online', 'Online')], default='venue', max_length=6, null=True)),
                ('event_type', models.CharField(blank=True, choices=[('conference', 'Conference Of Convention'), ('concert', 'Concert'), ('seminar', 'Seminar Or Talk'), ('festival', 'Festival Of Fair'), ('performance', 'Performance Or Live Show'), ('workshop', 'Class Training Or Workshop'), ('networking', 'Meeting Or Networking Event'), ('party', 'Party or Social Gathering'), ('attraction', 'Attraction'), ('appearance', 'Appearance Or Singing')], default='conference', max_length=20, null=True)),
                ('author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
