# Generated by Django 2.2.6 on 2020-04-06 16:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
