# Generated by Django 2.2.6 on 2020-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_auto_20200407_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text='address', max_length=500, null=True),
        ),
    ]
