# Generated by Django 2.0.3 on 2020-04-17 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_auto_20200416_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True, help_text='enter category description')),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, help_text='Enter city name', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, choices=[('venue', 'Venue'), ('online', 'Online')], default='online', max_length=6, null=True),
        ),
    ]
