# Generated by Django 2.0.3 on 2020-04-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_auto_20200417_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(help_text='Select category for this event', to='catalog.Category'),
        ),
    ]
