# Generated by Django 2.0.3 on 2020-04-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0030_auto_20200417_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='listing_type',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='event',
            name='website_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
