# Generated by Django 2.2.6 on 2020-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0032_event_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='featured',
            field=models.BooleanField(default=True, verbose_name='make it features ? '),
        ),
    ]
