# Generated by Django 2.0.3 on 2020-04-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0035_auto_20200418_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_image',
            field=models.ImageField(default='', upload_to='catalog/uploads'),
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='city',
            name='heading',
            field=models.CharField(default='', max_length=300),
        ),
    ]
