# Generated by Django 2.2.6 on 2020-06-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0040_auto_20200521_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('attendee_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('attedee_name', models.CharField(default='', max_length=300)),
                ('attendee_email', models.CharField(default='', max_length=100)),
                ('attendee_mobile', models.CharField(default='', max_length=30)),
                ('status', models.BooleanField(default=False)),
                ('tickit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Tickit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
