# Generated by Django 2.2.6 on 2020-06-15 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0042_attendee_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendee',
        ),
    ]
